insert into CarPlates (Plate, Brand, Model, Color, Year) values ('MXS-803', 'Subaru', 'Legacy', 'Pink', 2001);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('BFH-682', 'Cadillac', 'CTS', 'Yellow', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('QQG-264', 'Pontiac', 'Grand Prix', 'Fuscia', 1964);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('JUO-705', 'Infiniti', 'M', 'Crimson', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CICA-01', 'Pontiac', 'Grand Am', 'Aquamarine', 1991);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('YOLO-69', 'Acura', 'NSX', 'Red', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('MUO-260', 'Honda', 'Fit', 'Blue', 2007);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FRD-372', 'Subaru', 'Impreza', 'Blue', 2001);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CDT-612', 'Cadillac', 'Escalade EXT', 'Orange', 2012);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('XGI-570', 'Volvo', 'V40', 'Mauv', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('IUE-046', 'Ford', 'Windstar', 'Red', 2002);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('MIND-01', 'BMW', '325', 'Green', 2005);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('HJA-878', 'Jeep', 'Wrangler', 'Fuscia', 2007);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('MWF-312', 'Hyundai', 'Sonata', 'Purple', 2010);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('NEF-242', 'Ford', 'E250', 'Pink', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('GAH-767', 'Hyundai', 'Elantra', 'Turquoise', 1992);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('VKV-711', 'Cadillac', 'Escalade ESV', 'Blue', 2010);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('ROKI-77', 'BMW', 'X5', 'Aquamarine', 2011);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RB12-51', 'Opel', 'Astra', 'White', 2001);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('KLE-928', 'Oldsmobile', 'Cutlass Cruiser', 'Orange', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FIC-190', 'GMC', 'Sierra', 'Turquoise', 2008);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FOX-001', 'BMW', '5 Series', 'Teal', 2000);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('EWB-502', 'Mitsubishi', 'Raider', 'Crimson', 2009);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('WYB-302', 'Chrysler', 'Sebring', 'Red', 2009);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('TFX-013', 'GMC', 'Suburban 2500', 'Crimson', 1995);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('WJS-867', 'Jaguar', 'XK Series', 'Pink', 2001);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RB32-39', 'Opel', 'Astra', 'White', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RB99-01', 'Audi', 'R8', 'White', 2011);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('QJO-137', 'Hyundai', 'Accent', 'Crimson', 2000);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('ECX-124', 'Ford', 'F150', 'Teal', 2005);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('BGO-529', 'Pontiac', 'Bonneville', 'Blue', 2002);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('HUE-076', 'Honda', 'Passport', 'Aquamarine', 1997);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('GTZ-538', 'Mercury', 'Cougar', 'Indigo', 1996);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FAVAG-0', 'Mitsubishi', 'Pajero', 'Maroon', 1991);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('JRT-049', 'Panoz', 'Esperante', 'Yellow', 2007);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('DT11-55', 'Jeep', 'Liberty', 'Purple', 2009);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RQL-685', 'Lexus', 'CT', 'Orange', 2012);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RB10-91', 'Opel', 'Astra', 'White', 1992);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FOX-397', 'BMW', 'X5', 'Maroon', 2011);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('VIR-682', 'Porsche', '944', 'Green', 1991);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RB12-25', 'Opel', 'Astra', 'White', 2001);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('STJ-056', 'GMC', 'Yukon', 'Pink', 2008);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('LTW-583', 'Chevrolet', 'Astro', 'Maroon', 2005);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('NLB-711', 'Ford', 'Fusion', 'Fuscia', 2009);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('DT83-10', 'Mercedes-Benz', 'SL-Class', 'Aquamarine', 1991);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('XXW-871', 'Dodge', 'Ram 3500 Club', 'Turquoise', 1997);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RB12-05', 'Opel', 'Astra', 'White', 1991);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('OVD-998', 'Austin', 'Mini Cooper', 'Red', 1964);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('TWN-438', 'Mitsubishi', 'Truck', 'Puce', 1991);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('APY-798', 'Pontiac', 'Grand Prix', 'Blue', 1983);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CBI-960', 'Chrysler', 'PT Cruiser', 'Violet', 2003);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('KNV-421', 'Audi', 'S4', 'Indigo', 2013);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('YQN-381', 'Mercedes-Benz', 'C-Class', 'Khaki', 2006);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('ZGV-136', 'Volkswagen', 'Quantum', 'Green', 1984);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('INN-853', 'Chevrolet', 'Cobalt SS', 'Orange', 2009);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('NCI-829', 'Isuzu', 'Rodeo', 'Violet', 2002);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('UKG-515', 'Volkswagen', 'rio', 'Yellow', 1998);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('PARA-33', 'BMW', 'Z3', 'Khaki', 1999);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('HZW-072', 'Bentley', 'Continental Flying Spur', 'Fuscia', 2011);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('YES-706', 'Ford', 'F150', 'Goldenrod', 1992);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('UOZ-947', 'Cadillac', 'Escalade EXT', 'Violet', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('DT31-12', 'Nissan', 'Frontier', 'Puce', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('PJI-661', 'Buick', 'Somerset', 'Teal', 1987);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CICA-93', 'Mitsubishi', 'Diamante', 'Yellow', 2001);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('HUE-911', 'Porsche', '911', 'Red', 1996);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('ARP-034', 'Infiniti', 'G35', 'Purple', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('BELGA-1', 'Volkswagen', 'GOLF III', 'Violet', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('MAV-166', 'Dodge', 'Ramcharger', 'Turquoise', 1992);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('PFG-476', 'Chevrolet', 'Astro', 'Aquamarine', 2005);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CMB-359', 'GMC', 'Sierra 3500', 'Blue', 2004);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('WMH-436', 'Infiniti', 'FX', 'Mauv', 2010);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('XPT-438', 'Dodge', 'Ram 2500', 'Violet', 1994);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('DT43-78', 'Lincoln', 'Continental', 'Crimson', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('OLJ-878', 'Dodge', 'Ram 1500', 'Puce', 2008);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FOP-700', 'Nissan', '200SX', 'Maroon', 1996);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('KWO-395', 'Cadillac', 'Fleetwood', 'Crimson', 1992);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('DT44-90', 'Jeep', 'Wrangler', 'Goldenrod', 1994);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('FPR-345', 'Ford', 'Mustang', 'Pink', 1990);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('JBW-793', 'Volkswagen', 'Cabriolet', 'Crimson', 1996);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('UWO-352', 'Kia', 'Sedona', 'Pink', 2010);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('WED-075', 'Chevrolet', 'Silverado 1500', 'Yellow', 2012);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('UWC-821', 'Dodge', 'Ram 1500', 'Yellow', 2008);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('GNB-782', 'Dodge', 'Aries', 'Pink', 1981);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('VNX-213', 'Pontiac', 'Grand Prix', 'Khaki', 1983);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('LCF-210', 'Chevrolet', 'Camaro', 'Red', 1981);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('PZX-840', 'Toyota', 'Tacoma', 'Aquamarine', 2012);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('XWF-234', 'Chevrolet', 'HHR', 'Yellow', 2006);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('QSQ-178', 'Toyota', '4Runner', 'Turquoise', 1995);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('QQW-646', 'Ford', 'Flex', 'Turquoise', 2013);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('DT43-38', 'Porsche', '924 S', 'Violet', 1987);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CXA-267', 'GMC', 'Yukon', 'Green', 1998);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('RJE-927', 'Dodge', 'Viper', 'Turquoise', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('QQX-351', 'Plymouth', 'Grand Voyager', 'Orange', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('SOL-398', 'Chevrolet', 'SSR', 'Turquoise', 2006);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('WUL-758', 'Jaguar', 'X-Type', 'Indigo', 2006);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('ZQF-681', 'Chrysler', 'New Yorker', 'Mauv', 1994);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('CXX-648', 'Plymouth', 'Volare', 'Aquamarine', 1976);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('NBN-073', 'Mitsubishi', 'Raider', 'Fuscia', 2009);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('EIA-496', 'Oldsmobile', '88', 'Maroon', 1994);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('YIY-991', 'Subaru', 'Alcyone SVX', 'Aquamarine', 1993);
insert into CarPlates (Plate, Brand, Model, Color, Year) values ('TIBI-01', 'BMW', 'Z4 M', 'Red', 2006);
